In [1]:
import tensorflow as tf 

node1 = tf.constant (3.0, tf.float32)
node2 = tf.constant(4.0)

print(node1, node2)

tf.Tensor(3.0, shape=(), dtype=float32) tf.Tensor(4.0, shape=(), dtype=float32)


In [5]:
print(tf.__version__)

2.10.0


In [6]:
import numpy as np 

numpy_array = np.ones([5,5])

print(numpy_array)
print(numpy_array.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(5, 5)


In [7]:
numpy_vector = np.asarray([[3.,5.,3.,2.,2.]])

print(numpy_vector)
print(numpy_vector.shape)

[[3. 5. 3. 2. 2.]]
(1, 5)


In [8]:
tensor = tf.matmul(numpy_array, numpy_vector.T)
print(tensor)

tf.Tensor(
[[15.]
 [15.]
 [15.]
 [15.]
 [15.]], shape=(5, 1), dtype=float64)
