In [1]:
import tensorflow as tf 

node1 = tf.constant (3.0, tf.float32)
node2 = tf.constant(4.0)

print(node1, node2)

tf.Tensor(3.0, shape=(), dtype=float32) tf.Tensor(4.0, shape=(), dtype=float32)


In [5]:
print(tf.__version__)

2.10.0


In [6]:
import numpy as np 

numpy_array = np.ones([5,5])

print(numpy_array)
print(numpy_array.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(5, 5)


In [7]:
numpy_vector = np.asarray([[3.,5.,3.,2.,2.]])

print(numpy_vector)
print(numpy_vector.shape)

[[3. 5. 3. 2. 2.]]
(1, 5)


In [8]:
tensor = tf.matmul(numpy_array, numpy_vector.T)
print(tensor)

tf.Tensor(
[[15.]
 [15.]
 [15.]
 [15.]
 [15.]], shape=(5, 1), dtype=float64)


In [9]:
tensor_2 = tf.add(tensor, numpy_vector.T)
print(tensor_2)

tf.Tensor(
[[18.]
 [20.]
 [18.]
 [17.]
 [17.]], shape=(5, 1), dtype=float64)


In [10]:
tensor_3 = tf.multiply(tensor_2, 3)
print(tensor_3)

tf.Tensor(
[[54.]
 [60.]
 [54.]
 [51.]
 [51.]], shape=(5, 1), dtype=float64)


In [11]:
print(tensor_3.numpy())

[[54.]
 [60.]
 [54.]
 [51.]
 [51.]]


In [12]:
print(np.add(tensor_3, 9))

[[63.]
 [69.]
 [63.]
 [60.]
 [60.]]


In [13]:
@tf.function
def predict(x) :
    w = np.random.randn(1, x.shape[1])

    b = np.random.randn(x.shape[0], 1)

    return tf.matmul(x, w, transpose_b=True) + b

In [14]:
x = np.random.rand(10, 3)
print(x)

[[0.54094765 0.95809706 0.29901444]
 [0.96733003 0.47473627 0.26839344]
 [0.99988551 0.02945449 0.00583279]
 [0.11455575 0.66914346 0.75937729]
 [0.81565501 0.32153685 0.79192039]
 [0.40610276 0.22251178 0.20769227]
 [0.78141848 0.50282655 0.31821569]
 [0.29987921 0.35165731 0.68040182]
 [0.87044881 0.2946578  0.08533498]
 [0.14138021 0.50615976 0.34524425]]


In [15]:
y_hat = predict(x)
print(y_hat)

tf.Tensor(
[[ 0.51781776]
 [ 0.30472835]
 [ 0.01730386]
 [-0.98071492]
 [ 0.22809184]
 [ 0.32296932]
 [ 0.90305468]
 [ 0.74727294]
 [-0.32941881]
 [ 0.53666137]], shape=(10, 1), dtype=float64)


In [19]:
from tensorflow import keras 
import pandas as pd

file_path = keras.utils.get_file("iris.data", "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

In [20]:
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

df = pd.read_csv(file_path, names=column_names)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [21]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [22]:
df.head(n=10)

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [23]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [24]:
x = df[column_names[:-1]]
print(type(x))

<class 'pandas.core.frame.DataFrame'>


In [25]:
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [26]:
np_array = x[:5].to_numpy()

print(np_array)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [27]:
tensor = tf.multiply(np_array, 1.0)
print(tensor)

tf.Tensor(
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]], shape=(5, 4), dtype=float64)


In [30]:
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

df = pd.read_csv(file_path, names=column_names)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [31]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [34]:
df_one_hot = pd.get_dummies(df, prefix=None, columns=['class'])

df_one_hot.head()

sepal_length  sepal_width  petal_length  petal_width  class_Iris-setosa  \
0           5.1          3.5           1.4          0.2                  1   
1           4.9          3.0           1.4          0.2                  1   
2           4.7          3.2           1.3          0.2                  1   
3           4.6          3.1           1.5          0.2                  1   
4           5.0          3.6           1.4          0.2                  1   

   class_Iris-versicolor  class_Iris-virginica  
0                      0                     0  
1                      0                     0  
2                      0                     0  
3                      0                     0  
4                      0                     0

In [36]:
df_one_hot = pd.get_dummies(df, prefix=None, columns=['class'], drop_first=True)

df_one_hot.head()

sepal_length  sepal_width  petal_length  petal_width  \
0           5.1          3.5           1.4          0.2   
1           4.9          3.0           1.4          0.2   
2           4.7          3.2           1.3          0.2   
3           4.6          3.1           1.5          0.2   
4           5.0          3.6           1.4          0.2   

   class_Iris-versicolor  class_Iris-virginica  
0                      0                     0  
1                      0                     0  
2                      0                     0  
3                      0                     0  
4                      0                     0

In [37]:
df_one_hot.tail()

sepal_length  sepal_width  petal_length  petal_width  \
145           6.7          3.0           5.2          2.3   
146           6.3          2.5           5.0          1.9   
147           6.5          3.0           5.2          2.0   
148           6.2          3.4           5.4          2.3   
149           5.9          3.0           5.1          1.8   

     class_Iris-versicolor  class_Iris-virginica  
145                      0                     1  
146                      0                     1  
147                      0                     1  
148                      0                     1  
149                      0                     1

In [1]:
import tensorflow as tf
from tensorflow import keras 
import numpy as np

# 1D tensor 

_a = np.ones(5)
_a = tf.multiply(_a, 1)
print(_a)
print(_a.shape)

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float64)
(5,)


In [2]:
# 2D tensor

_b = np.ones([2,5])
_b = tf.multiply(_b, 1)
print(_b)
print(_b.shape)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(2, 5), dtype=float64)
(2, 5)


In [4]:
# 3D tensor

file_path = keras.utils.get_file('dog.999.jpg', 'https://direct2farm.in/public/uploads/2ead97c4-a54a-4149-84a5-6ec36e0f8fc4.jpg')

471343/471343 [==============================] - 1s 2us/step


In [5]:
img_raw = tf.io.read_file(file_path)
print(repr(img_raw)[:100] + "...")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x01,\x01,\x...


In [7]:
img_tensor = tf.image.decode_image(img_raw)

print(img_tensor.shape)
print(img_tensor.dtype)

(3508, 2481, 3)
<dtype: 'uint8'>


In [8]:
img_final = tf.image.resize(img_tensor, [192, 192])

img_final = img_final/255.0

print(img_final.shape)
print(img_final.numpy().min())
print(img_final.numpy().max())


(192, 192, 3)
0.0
1.0


In [9]:
print(_b[:, :3])

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float64)


In [10]:
print(tf.reshape(_b, [-1]))

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float64)


In [11]:
print(tf.reshape(_b, [2,5,1]))

tf.Tensor(
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]], shape=(2, 5, 1), dtype=float64)


In [36]:
fashion_mnist = keras.datasets.fashion_mnist 
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

train_images = train_images/255.0
test_images = test_images/255.0



4422102/4422102 [==============================] - 0s 0us/step


In [37]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(784, activation='relu'),
    keras.layers.Dense(784, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

model.fit(train_images, train_labels, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.4678 - accuracy: 0.8294
Epoch 2/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.3540 - accuracy: 0.8708
Epoch 3/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.3207 - accuracy: 0.8810
Epoch 4/10
1875/1875 [==============================] - 16s 8ms/step - loss: 0.2964 - accuracy: 0.8898
Epoch 5/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.2762 - accuracy: 0.8967
Epoch 6/10
1875/1875 [==============================] - 16s 8ms/step - loss: 0.2632 - accuracy: 0.9008
Epoch 7/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.2506 - accuracy: 0.9051
Epoch 8/10
1875/1875 [==============================] - 14s 8ms/step - loss: 0.2399 - accuracy: 0.9075
Epoch 9/10
1875/1875 [==============================] - 14s 8ms/step - loss: 0.2277 - accuracy: 0.9135
Epoch 10/10
1875/1875 [==============================] - 14s 8ms/step - l

In [38]:
print(model.summary())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense_14 (Dense)            (None, 784)               615440    
                                                                 
 dense_15 (Dense)            (None, 784)               615440    
                                                                 
 dense_16 (Dense)            (None, 10)                7850      
                                                                 
Total params: 1,238,730
Trainable params: 1,238,730
Non-trainable params: 0
_________________________________________________________________
None
